apiVersion: apps/v1
kind: Deployment
metadata:
  name: python-test
spec:
  replicas: 1
  selector:
    matchLabels:
      app: python-test
  template:
    metadata:
      labels:
        app: python-test
    spec:
      containers:
        - name: python-test
          image: test-backend-routes  # This is the image we built
          imagePullPolicy: Never  # Prevents Kubernetes from trying to pull the image from a registry
          ports:
            - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: python-test-service
spec:
  selector:
    app: python-test
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
