apiVersion: apps/v1
kind: Deployment
metadata:
  name: hotel-manager
spec:
  replicas: 1
  selector:
    matchLabels:
      app: hotel-manager
  template:
    metadata:
      labels:
        app: hotel-manager
    spec:
      containers:
      - name: hotel-manager
        image: hotel-manager:latest
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 5000
        env: # better using ConfigMap, but i left them here for simplicity)
        - name: POSTGRES_HOST
          value: "hotel-manager-db"
        - name: POSTGRES_USER
          value: "admin"
        - name: POSTGRES_PASSWORD
          value: "password"
        - name: POSTGRES_DB
          value: "hotel_manager"
        - name: POSTGRES_PORT
          value: "5432"
---
apiVersion: v1
kind: Service
metadata:
  name: hotel-manager
spec:
  selector:
    app: hotel-manager
  ports:
    - protocol: TCP
      port: 5000
      targetPort: 5000
  type: ClusterIP
