apiVersion: apps/v1
kind: Deployment
metadata:
  name: vehicle-sales-backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: vehicle-sales-backend
  template:
    metadata:
      labels:
        app: vehicle-sales-backend
    spec:
      containers:
      - name: vehicle-sales-backend
        image: vehicle-sales-backend:latest
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 5000
        env: # better using ConfigMap, but i left them here for simplicity)
        - name: POSTGRES_HOST
          value: "vehicle-sales-db"
        - name: POSTGRES_USER
          value: "admin"
        - name: POSTGRES_PASSWORD
          value: "password"
        - name: POSTGRES_DB
          value: "vehicle-sales"
        - name: POSTGRES_PORT
          value: "5432"
---
apiVersion: v1
kind: Service
metadata:
  name: vehicle-sales-backend
spec:
  selector:
    app: vehicle-sales-backend
  ports:
    - protocol: TCP
      port: 5000
      targetPort: 5000
  type: ClusterIP
