apiVersion: apps/v1
kind: Deployment
metadata:
  name: vehicle-sales-frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: vehicle-sales-frontend
  template:
    metadata:
      labels:
        app: vehicle-sales-frontend
    spec:
      containers:
      - name: vehicle-sales-frontend
        image: vehicle-sales-frontend:latest
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 3000
---
apiVersion: v1
kind: Service
metadata:
  name: vehicle-sales-frontend
spec:
  selector:
    app: vehicle-sales-frontend
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000
  type: NodePort 