apiVersion: apps/v1
kind: Deployment
metadata:
  name: hotel-manager-db
spec:
  replicas: 1
  selector:
    matchLabels:
      app: hotel-manager-db
  template:
    metadata:
      labels:
        app: hotel-manager-db
    spec:
      containers:
      - name: postgres
        image: postgres:15
        ports:
        - containerPort: 5432
        env:
        - name: POSTGRES_USER
          value: "admin"
        - name: POSTGRES_PASSWORD
          value: "password"
        - name: POSTGRES_DB
          value: "hotel_manager"
        volumeMounts:
        - name: postgres-data
          mountPath: /var/lib/postgresql/data
      volumes:
        - name: postgres-data
          emptyDir: {}
---
apiVersion: v1
kind: Service
metadata:
  name: hotel-manager-db
spec:
  selector:
    app: hotel-manager-db
  ports:
    - protocol: TCP
      port: 5432
      targetPort: 5432
  type: ClusterIP
